import type { Senior, Session, Review, JuniorProfile } from './types';

const avatarFor = (seed: string) =>
  `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(seed)}&backgroundColor=0d9488,0f766e,115e59,14b8a6,2dd4bf&textColor=ffffff&fontWeight=600`;

const juniorAvatarFor = (seed: string) =>
  `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(seed)}&backgroundColor=f59e0b,d97706,b45309,ea580c&textColor=ffffff&fontWeight=600`;

function buildSlots(baseDay: number): { id: string; date: string; time: string; available: boolean }[] {
  const times = ['09:00', '11:00', '14:00', '16:00', '18:00'];
  const slots = [];
  for (let d = 0; d < 7; d++) {
    const date = new Date();
    date.setDate(date.getDate() + baseDay + d);
    const dateStr = date.toISOString().split('T')[0];
    for (const time of times) {
      slots.push({
        id: `${dateStr}-${time}`,
        date: dateStr,
        time,
        available: Math.random() > 0.35,
      });
    }
  }
  return slots;
}

export const seniors: Senior[] = [
  {
    id: 's1',
    name: 'Priya Sharma',
    title: 'Staff Software Engineer',
    company: 'Google',
    domain: 'Backend Systems',
    expertise: ['System Design', 'Distributed Systems', 'Go', 'Kubernetes'],
    role: 'Backend',
    bio: 'I have spent the last decade building large-scale backend infrastructure at Google and previously at Stripe. I love helping early-career engineers think clearly about system design, career trajectory, and the craft of writing software that lasts.',
    experience: 11,
    credibilityScore: 96,
    rating: 4.9,
    reviewCount: 142,
    sessionCount: 318,
    availability: 'available',
    avatar: avatarFor('Priya Sharma'),
    location: 'Bengaluru, India',
    slots: buildSlots(1),
    achievements: ['Tech Lead for Ads Infrastructure', 'Speaker at KubeCon 2023', 'Mentor at Google STEP'],
  },
  {
    id: 's2',
    name: 'Marcus Chen',
    title: 'Principal Frontend Engineer',
    company: 'Meta',
    domain: 'Frontend & Web',
    expertise: ['React', 'Performance', 'Design Systems', 'TypeScript'],
    role: 'Frontend',
    bio: 'Frontend specialist focused on performance, accessibility, and building design systems that scale across thousands of engineers. I have mentored dozens of juniors into mid-level and senior roles.',
    experience: 13,
    credibilityScore: 94,
    rating: 4.8,
    reviewCount: 98,
    sessionCount: 210,
    availability: 'limited',
    avatar: avatarFor('Marcus Chen'),
    location: 'San Francisco, USA',
    slots: buildSlots(2),
    achievements: ['Led React 18 migration at Meta', 'Author of "Render Fast"', 'Accessibility advocate'],
  },
  {
    id: 's3',
    name: 'Aisha Patel',
    title: 'Director of Data Science',
    company: 'Netflix',
    domain: 'Data & ML',
    expertise: ['Machine Learning', 'Python', 'Recommendation Systems', 'A/B Testing'],
    role: 'Data',
    bio: 'I lead the recommendation engine team at Netflix. Passionate about helping students transition into data science and ML engineering roles with practical, project-first guidance.',
    experience: 15,
    credibilityScore: 98,
    rating: 5.0,
    reviewCount: 176,
    sessionCount: 402,
    availability: 'available',
    avatar: avatarFor('Aisha Patel'),
    location: 'Los Gatos, USA',
    slots: buildSlots(0),
    achievements: ['Built Netflix top-10 row', 'PhD from Stanford', 'Keynote at MLConf'],
  },
  {
    id: 's4',
    name: 'David Okonkwo',
    title: 'Senior DevOps Engineer',
    company: 'AWS',
    domain: 'DevOps & Cloud',
    expertise: ['AWS', 'Terraform', 'CI/CD', 'Site Reliability'],
    role: 'DevOps',
    bio: 'Cloud infrastructure engineer who has designed and operated platforms serving millions of requests per second. I help juniors build confidence with real-world DevOps practices.',
    experience: 9,
    credibilityScore: 91,
    rating: 4.7,
    reviewCount: 64,
    sessionCount: 130,
    availability: 'available',
    avatar: avatarFor('David Okonkwo'),
    location: 'Dublin, Ireland',
    slots: buildSlots(1),
    achievements: ['AWS Hero', 'Built multi-region failover', 'Open-source contributor'],
  },
  {
    id: 's5',
    name: 'Elena Rossi',
    title: 'Engineering Manager',
    company: 'Spotify',
    domain: 'Engineering Management',
    expertise: ['Leadership', 'Career Growth', 'Interview Prep', 'Team Building'],
    role: 'Management',
    bio: 'I manage a team of 12 engineers at Spotify. I specialize in helping juniors navigate their first years — from imposter syndrome to promotion, to deciding whether management is right for them.',
    experience: 12,
    credibilityScore: 93,
    rating: 4.9,
    reviewCount: 121,
    sessionCount: 245,
    availability: 'limited',
    avatar: avatarFor('Elena Rossi'),
    location: 'Stockholm, Sweden',
    slots: buildSlots(3),
    achievements: ['Promoted 8 engineers to senior', 'Spotify culture ambassador', 'Coach at LeadDev'],
  },
  {
    id: 's6',
    name: 'Raj Mehta',
    title: 'Mobile Engineering Lead',
    company: 'Uber',
    domain: 'Mobile Development',
    expertise: ['iOS', 'Swift', 'Android', 'Mobile Architecture'],
    role: 'Mobile',
    bio: 'I build mobile apps used by millions daily. I enjoy guiding students through mobile development fundamentals and helping them ship their first real apps.',
    experience: 10,
    credibilityScore: 90,
    rating: 4.6,
    reviewCount: 52,
    sessionCount: 98,
    availability: 'booked',
    avatar: avatarFor('Raj Mehta'),
    location: 'Gurugram, India',
    slots: buildSlots(2),
    achievements: ['Led Uber Rider rewrite', '2 apps on App Store', 'Swift community speaker'],
  },
  {
    id: 's7',
    name: 'Sofia Garcia',
    title: 'Security Engineer',
    company: 'Cloudflare',
    domain: 'Security',
    expertise: ['Application Security', 'Penetration Testing', 'Cryptography', 'Threat Modeling'],
    role: 'Security',
    bio: 'Security engineer focused on protecting applications at scale. I help juniors break into security — one of the most in-demand and under-taught domains in engineering.',
    experience: 8,
    credibilityScore: 92,
    rating: 4.8,
    reviewCount: 47,
    sessionCount: 89,
    availability: 'available',
    avatar: avatarFor('Sofia Garcia'),
    location: 'Lisbon, Portugal',
    slots: buildSlots(1),
    achievements: ['Found CVE in major framework', 'OSCP certified', 'Bug bounty top 100'],
  },
  {
    id: 's8',
    name: 'James Wilson',
    title: 'VP of Engineering',
    company: 'Shopify',
    domain: 'Engineering Leadership',
    expertise: ['Architecture', 'Scaling Teams', 'Hiring', 'Product Strategy'],
    role: 'Management',
    bio: 'I have scaled engineering teams from 5 to 200+ engineers. I mentor juniors who aspire to leadership and help them understand how to create outsized impact early in their careers.',
    experience: 18,
    credibilityScore: 97,
    rating: 4.9,
    reviewCount: 88,
    sessionCount: 156,
    availability: 'limited',
    avatar: avatarFor('James Wilson'),
    location: 'Ottawa, Canada',
    slots: buildSlots(4),
    achievements: ['Scaled Shopify Checkout', 'Hired 150+ engineers', 'Advisor at YC'],
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    seniorId: 's1',
    juniorName: 'Alex Kim',
    juniorAvatar: juniorAvatarFor('Alex Kim'),
    rating: 5,
    date: '2026-08-20',
    comment: 'Priya completely changed how I approach system design. She walked me through a real architecture problem step by step and I finally understood the trade-offs. Incredibly patient and insightful.',
  },
  {
    id: 'r2',
    seniorId: 's1',
    juniorName: 'Nina Brooks',
    juniorAvatar: juniorAvatarFor('Nina Brooks'),
    rating: 5,
    date: '2026-08-12',
    comment: 'Best mentoring session I have had. Priya gave me a concrete 3-month plan to level up on distributed systems and it landed me a backend role.',
  },
  {
    id: 'r3',
    seniorId: 's1',
    juniorName: 'Tom Lee',
    juniorAvatar: juniorAvatarFor('Tom Lee'),
    rating: 4,
    date: '2026-07-30',
    comment: 'Very knowledgeable and structured. Would have liked a bit more time for Q&A but the content was excellent.',
  },
  {
    id: 'r4',
    seniorId: 's3',
    juniorName: 'Maya Singh',
    juniorAvatar: juniorAvatarFor('Maya Singh'),
    rating: 5,
    date: '2026-08-22',
    comment: 'Aisha helped me pivot from a stats background into ML engineering. Her project-first approach made all the difference. I got an internship at a top firm.',
  },
  {
    id: 'r5',
    seniorId: 's2',
    juniorName: 'Chris Park',
    juniorAvatar: juniorAvatarFor('Chris Park'),
    rating: 5,
    date: '2026-08-15',
    comment: 'Marcus knows performance optimization inside out. He helped me cut our app load time in half. Practical, no-fluff mentoring.',
  },
];

export const juniorProfile: JuniorProfile = {
  name: 'Rohan Verma',
  title: 'Final-year CS Student',
  email: 'rohan.verma@example.com',
  avatar: juniorAvatarFor('Rohan Verma'),
  credibilityScore: 72,
  university: 'BITS Pilani',
  year: 'Final Year',
  interests: ['Backend Systems', 'System Design', 'Go', 'Cloud'],
  sessionsCompleted: 6,
  seniorsSaved: 4,
  goals: [
    { id: 'g1', title: 'Land a backend internship', progress: 75 },
    { id: 'g2', title: 'Complete 10 mentoring sessions', progress: 60 },
    { id: 'g3', title: 'Build a production-grade API', progress: 45 },
  ],
};

const today = new Date();
const inDays = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};

export const sessions: Session[] = [
  {
    id: 'ses1',
    seniorId: 's1',
    seniorName: 'Priya Sharma',
    seniorAvatar: avatarFor('Priya Sharma'),
    juniorName: 'Rohan Verma',
    date: inDays(2),
    time: '16:00',
    duration: 45,
    topic: 'System design for a URL shortener',
    status: 'upcoming',
    meetingLink: 'https://meet.example.com/ses1',
    notes: 'Come prepared with a rough architecture sketch.',
  },
  {
    id: 'ses2',
    seniorId: 's3',
    seniorName: 'Aisha Patel',
    seniorAvatar: avatarFor('Aisha Patel'),
    juniorName: 'Rohan Verma',
    date: inDays(5),
    time: '14:00',
    duration: 60,
    topic: 'Transitioning into ML engineering',
    status: 'upcoming',
    meetingLink: 'https://meet.example.com/ses2',
  },
  {
    id: 'ses3',
    seniorId: 's2',
    seniorName: 'Marcus Chen',
    seniorAvatar: avatarFor('Marcus Chen'),
    juniorName: 'Rohan Verma',
    date: inDays(-6),
    time: '11:00',
    duration: 45,
    topic: 'React performance optimization',
    status: 'completed',
    meetingLink: 'https://meet.example.com/ses3',
    hasFeedback: true,
  },
  {
    id: 'ses4',
    seniorId: 's4',
    seniorName: 'David Okonkwo',
    seniorAvatar: avatarFor('David Okonkwo'),
    juniorName: 'Rohan Verma',
    date: inDays(-13),
    time: '18:00',
    duration: 60,
    topic: 'Setting up CI/CD with GitHub Actions',
    status: 'completed',
    meetingLink: 'https://meet.example.com/ses4',
    hasFeedback: true,
  },
  {
    id: 'ses5',
    seniorId: 's5',
    seniorName: 'Elena Rossi',
    seniorAvatar: avatarFor('Elena Rossi'),
    juniorName: 'Rohan Verma',
    date: inDays(-20),
    time: '16:00',
    duration: 45,
    topic: 'Preparing for my first engineering interview',
    status: 'completed',
    meetingLink: 'https://meet.example.com/ses5',
    hasFeedback: false,
  },
];

export const savedSeniorIds = ['s1', 's3', 's5', 's8'];

export const filterOptions = {
  roles: ['Backend', 'Frontend', 'Data', 'DevOps', 'Management', 'Mobile', 'Security'],
  companies: ['Google', 'Meta', 'Netflix', 'AWS', 'Spotify', 'Uber', 'Cloudflare', 'Shopify'],
  domains: ['Backend Systems', 'Frontend & Web', 'Data & ML', 'DevOps & Cloud', 'Engineering Management', 'Mobile Development', 'Security', 'Engineering Leadership'],
  expertise: ['System Design', 'Distributed Systems', 'Go', 'Kubernetes', 'React', 'Performance', 'Design Systems', 'TypeScript', 'Machine Learning', 'Python', 'AWS', 'Terraform', 'CI/CD', 'Leadership', 'Career Growth', 'iOS', 'Swift', 'Application Security', 'Cryptography', 'Architecture', 'Hiring'],
  availability: ['available', 'limited', 'booked'] as const,
};